#!/bin/bash

set -x

mv -r ./public/.git ./_git
rm -rf ./public
rm -rf ./static
mv _git public
mv public/_git public/.git
hugo
cd ./public
git pull
git add -A
git commit -m "build release"
git push
cd ..

