#!/bin/bash

set -x

rm -rf ./public
rm -rf ./static
hugo
cd ./public
git remote add origin https://github.com/wilvk/wilvk.github.io
cd ..
cd ./public
git pull
git add -A
git commit -m "build release"
git push
cd ..

