#!/bin/bash

set -x

rm -rf ./public
rm -rf ./themes/kiera
git clone https://github.com/wilvk/hugo-kiera themes/kiera
git clone https://github.com/wilvk/wilvk.github.io public
hugo -D
cd ./public
git add .
git commit -m "build release"
git push --set-upstream origin master
cd ..
rm -rf ./public
