baseurl = "http://me.wvk.au"
title = "Will's Blog"
copyright = "Copyright &copy; 2018 - Willem van Ketwich"
canonifyurls = true
theme = "lightbi"

pagination.pagerSize = 3

summaryLength = 20
enableEmoji = true
pygmentsCodeFences = true

## Hugo Built-in Features
#disqusShortname = "wilvk-github-io"
googleAnalytics = "UA-122351489-2"
enableRobotsTXT = true

builddrafts = false
languageCode = "en-US"

[params]
    tagline = "Just a dude that does stuff.. mostly with computers."
    author.name = "Willem van Ketwich"
    author.github = "wilvk"
    author.linkedin = "willvk"
    author.twitter = "wilvk"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 10
    identifier = "blog"
    url = "/posts/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 20
    url = "/about/"
