baseurl = "https://blog.seso.io"
title = "Will's Blog"
copyright = "Copyright &copy; 2017 - Willem van Ketwich"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

## Hugo Built-in Features
disqusShortname = "wilvk-github-io"
googleAnalytics = "UA-122351489-2"
enableRobotsTXT = true

builddrafts = false
languageCode = "en-US"

[author]
    name = "Willem van Ketwich"
    github = "wilvk"
    linkedin = "willvk"
    twitter = "wilvk"

[params]
    tagline = "Just a dude that does stuff.. mostly with computers."

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 10
    identifier = "blog"
    url = "/posts/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 20
    url = "/about/"

